### ISSUE TITLE
why datum document does not have uid?

### ISSUE THREAD

**Issue by prjemian** [NSLS-II/bluesky#1070]
Working to update the [`SpecFileWriter()`](https://github.com/BCDA-APS/APS_BlueSky_tools/issues/29) to be compatible with AreaDetector and new (since 2017-09) API.  Found two new documents in the stream from `bp.count()`: *resource* and *datum*.

## Expected Behavior
expect to find a `uid` in every document emitted from RunEngine

## Current Behavior
`uid` is MIA

## Possible Solution
Ensure `uid` is added to *all* documents emitted by RunEngine.

## Steps to Reproduce (for bugs)
See https://github.com/BCDA-APS/APS_BlueSky_tools/issues/29

## Context
Trying to solve one problem and this came up.

## Your Environment
'OPHYD_VERSION': '1.2.0', 
'BLUESKY_VERSION': '1.3.3'
arch = linux_x86-64

**Comment by prjemian** [comment]
example code to reproduce problem here:  https://github.com/prjemian/ipython_mintvm/blob/master/profile_bluesky/startup/local_code/adsimdet_specwriter.py

**Comment by prjemian** [comment]
requires working instance of EPICS AreaDetector ADSimDetector `13SIM1:` example

**Comment by CJ-Wright** [comment]
they are called `datum_id` https://github.com/NSLS-II/event-model/blob/master/event_model/schemas/datum.json#L11

**Comment by prjemian** [comment]
I see that.  But why?  Particularly, why does this document type have to be different than the others?

**Comment by prjemian** [comment]
This kind of special case code results:

```
        if uid is None:
            # datum document does not have a "uid"
            logger.debug("{} document, uid={}".format(key, document["datum_id"]))
        else:
            # all other documents have a "uid"
            logger.debug("{} document, uid={}".format(key, document["uid"]))
```

**Comment by CJ-Wright** [comment]
xref: https://github.com/NSLS-II/ophyd/pull/563

**Comment by prjemian** [comment]
Great backtrail on this.  Then it is a simple thing to add a uid to this document type and not break any existing code, correct?  The result is that this document type will then be consistent with what is expected for all documents from the RunEngine.

**Comment by CJ-Wright** [comment]
Sure, I was the one who raised the issue in the first place, so I remembered where it was.

**Comment by jrmlhermitte** [comment]
Just to paste @danielballan 's comment on the thread xrefed here:

> This actual reason that this name is inconsistent is probably accidental. Renaming it would break a lot of code. Having two names for the same thing introduces opportunity for error and increases overhead. Our retconned justification for the different name is that datum_id is the only id that isn't a randomly-generated UUID4.

Should we reconsider voting on this? I'm indifferent. I think getting this issue is a good thing. Making assumptions rather than [referring to the schema](https://github.com/NSLS-II/event-model/blob/master/event_model/schemas/datum.json#L11) is probably not a good thing in the long run.
@prjemian were you aware of the schema? I wonder if it should be made more transparent/better documented? (I didn't use this for a long time!)

**Comment by danielballan** [comment]
@jrmlhermitte Can you put a PR against the Documents page in bluesky adding a link to the event-model repo?

**Comment by jrmlhermitte** [comment]
add [here](https://github.com/NSLS-II/docs/pull/85/files) thanks!

**Comment by prjemian** [comment]
summarizing the various [document schema](https://github.com/NSLS-II/event-model/blob/master/event_model/schema):

* `uid` required : `run_start`, `event_descriptor`, `resource`, `event`, `bulk_events`, `run_stop`
* not required : `datum`

The argument why `datum_id` should not be renamed is clear and I support that.  

Missing from the discussion above and in NSLS-II/ophyd#563 is why the `datum` document must be the only document schema that is missing a required `uid`.  The requirement of `uid` would be easy to add and would make the `datum` document like the others.  The `uid` would not be in conflict with the `datum_id`.  Without a `uid`, this is an arbitrary inconsistency.

**Comment by danielballan** [comment]
I think there is still confusion about the current state of the system. Datum documents have a unique ID that is called `datum_id`. Why do they need a second unique ID named `uid`?

**Comment by prjemian** [comment]
There is no confusion.  

[Restating](https://github.com/NSLS-II/bluesky/issues/1070#issuecomment-404335442), there was [discussion](https://github.com/NSLS-II/bluesky/issues/1070#issuecomment-404316386) why `datum_id` could not be renamed.  Fine.  No need to discuss `datum_id` further.

All other documents have `uid` but this one.  This inconsistency is exposed when handling documents in a generic handler such as the [SpecWriterCallback](https://github.com/BCDA-APS/APS_BlueSky_tools/issues/29), *because of this one type of document*.

Why must `datum` documents be different than the others in this regard?  Is there something else to the resistance to make this document type consistent with the others?

**Comment by danielballan** [comment]
I see. Sorry, @prjemian, I was moving a bit too quickly between tabs doing issue triage and did not properly refresh myself on the state of the discussion.

I understand the annoyance of this inconsistency and how it manifests in consumers like SpecWriterCallback. But I'm still not 100% sure I understand your proposal. Are you proposing adding a `uid` to `datum` that would have the same value as its `datum_id`?

**Comment by prjemian** [comment]
Almost exactly.  The `uid` would have a proper uuid, like the other documents.  The `datum_id` has a uuid + "/%d".  Not that I care, but it's different in style than the others.

**Comment by danielballan** [comment]
It's a reasonable proposal. One reason we haven't done this yet is that generating a UUID4 per Datum is surprisingly expensive. We have found that obtaining the required entropy was actually the bottleneck for acquisition at one of our beamlines. Incrementing an integer is cheap. It's possible that we should have done Events the same way. At the time, we wanted to allow multiple documents with the same sequence number due to rewinding... and I'm not sure we were wrong.

**Comment by prjemian** [comment]
Understood.  That is the argument that has been missing all along.  Making a uuid is expensive.
I'm not opposed to using the same value in both `datum_id` and `-uid`.

**Comment by danielballan** [comment]
In my view, putting the same value in two places is slightly worse than dealing with the inconsistency in names, especially since datum_id is already different than the others due to its `uuid4/int` structure and will have to be handled specially by some consumers anyway. But I do not feel strongly about this.

**Comment by stuartcampbell** [comment]
How do we feel about leaning on mongodb for this and let the db server take the load of generating the  `uuid` ?  I'm not sure it's a good idea - but just for discussion.. 😄

**Comment by prjemian** [comment]
I agree with https://github.com/NSLS-II/bluesky/issues/1070#issuecomment-405708492 as well.  Making mongodb produce the UUID seems attractive but would not solve the original problem.  It also makes this document type dependent on the databroker backend.

The discussion has been good to identify the basic motivations for the current implementation.  Summarizing:

* `datum_id` was optimized for low overhead, based on a common UUID and an incrementing integer
* community was built around this exact name, thus changing it to `uid` would cause problems
* creating a new UUID for each `datum` document introduces overhead, perhaps unacceptable
* duplicating `datum_id` into `uid` to maintain a common document schema seems wasteful

Having agreed to keep the current implementation, I could close this issue without further action.  Agree?

**Comment by tacaswell** [comment]
Agreement seems to be to take no action on this so closing.

If we could do it again, would probably use the name 'uid' vs 'datum_id', but that ship has sailed.  It could be argued that all documents require special-case handling because they contain different kinds of information.

@stuartcampbell The problem with having mongo create the unique ID is that we would then have to bake that into RE and feed back information to the source of the documents about what the ID is (as we use `datum_id` as a foreign key).
