### ISSUE TITLE
09 - Monitoring and Muxing det2 not defined

### ISSUE THREAD

**Issue by robmarkcole** [NSLS-II/bluesky#1083]
On https://try.nsls2.bnl.gov in `09 - Monitoring and Muxing.ipynb` the `det2` is not defined:

```
NameError                                 Traceback (most recent call last)
<ipython-input-7-16b24b142bc7> in <module>()
----> 1 RE(monitor_count([det, det2], [sig], delay=1), TimePrinter())

NameError: name 'det2' is not defined
```

The imports can be fixed with `from ophyd.sim import rand, det, det2, sig` except `TimePrinter()` which doesn't appear to be in the repo

Btw is there a repo for these notebooks?

**Comment by tacaswell** [comment]
Yikes, those have gotten away from us!

See https://github.com/NSLS-II/tutorial  In the tutorial there is a link to "BNL Deployment" which has notebooks + an enviroment that we know works! 

The notebooks on try.nsls2.bnl.gov are partially remixed, partially moved to `archive`.

**Comment by danielballan** [comment]
I think that "BNL Deployment" link was broken at the time @tacawell posted this, unfortunately, but everything is now cleaned up and redeployed. I reworked our deployment process so that thing shouldn't get away from us this badly again.

The fixed content is available on http://try.nsls2.bnl.gov and the BNL deployment, but the BNL deployment is more suitable for workshops and in-person events, so I would recommend sticking with http://try.nsls2.bnl.gov.

**Comment by danielballan** [comment]
Oh, this was superseded by the notebook titled "We'll Cross the Streams". Action item was to delete this one.
