### ISSUE TITLE
should the user decide when a scan has failed?

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/bluesky#1090]
I ask because we just had a scan fail because a physical limit.  this physical limit saved the equipment.  the data is still perfectly good.  in cases where there is a following error, the data can also be perfectly good.

however, if I use automated scripts, then this data would get skipped.  shouldn't the user decided if a scan is really useless?  much in the way that the user decides when pausing?

```python
~/.ipython/profile_collection/plans/03-plan.py in <module>()
----> 1 RE.stop()

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/run_engine.py in stop(self)
   1022         """
   1023         if self.state.is_idle:
-> 1024             raise TransitionError("RunEngine is already idle.")
   1025         print("Stopping: running cleanup and marking exit_status "
   1026               "as 'success'...")

TransitionError: RunEngine is already idle.

In [124]: db[-1].stop
namespace()
Out[124]: 
{'run_start': '59cec819-b1b1-48fa-84cc-072ff727cdb9',
 'time': 1534732632.5627072,
 'uid': 'fe0ee73e-dcb2-4d53-824a-42d9d81a5e95',
 'exit_status': 'fail',
 'num_events': {'baseline': 2, 'primary': 114},
 'reason': 'MoveStatus(done=True, pos=ow, elapsed=22.7, success=False, settle_time=0.1)'}

In [125]: 
```

**Comment by danielballan** [comment]
I think the "paused and stopped/aborted" case and the "errored out" case are different situations.

When the RunEngine is paused by the user, all bluesky knows is that everything seems fine (no errors) but that the user wanted to interrupt for some reason. Bluesky is beholden to the user to explain _why_ because it has nothing else to go on.

But in the situation where a scan errors out, bluesky _does_ know something about what went wrong, and I think bluesky should always write down the error that it sees _somewhere_, no matter whether the user thinks that error impacted or did not impact the science. If, in later analysis, that data produces an outlier, it would be good to know that there is reason to be suspicious about it.

Perhaps the best solution is tagging. It's been on our to-do list for awhile, and it's technically trivial to implement. We just need to build some tooling to make it usable. I'm imaging something like this:

1. All runs get labeled with an 'exit_status', as they do today. When a scan errors out, it's exit_status will always be 'fail', as it is today.
2. Separately, after they complete, runs  are optionally tagged as good or bad by the user.
3. The scripts use logic like:
   exit_status == 'abort' -> bad  # user paused and did RE.abort()
   exit_status == 'success' -> good  # normal operation or pause + RE.stop()
   exit_status == 'fail' & 'good' in tags -> good  # scan errored out, but user labeled it as good
   exit_status == 'fail' -> bad  # scan errored out and user said nothing
   'bad' in tags -> bad  # scan exited fine but user noticed after it completed that it should have been aborted (shutter was closed or whatever)

Would that address the problem?

**Comment by prjemian** [comment]
agreed

exit_status should always reflect the conditions and results that were expected programmtically by the plan.  Allowance for the user to assign a tab that asserts something like "this failed scan is still useful for ___ processing" *after* the plan is complete (and the stop document has been issued), perhaps through the databroker.

**Comment by tacaswell** [comment]
Closing this as there seems to be consensus that this is the desirable behavior at the bluesky level.  We need a better user-annotation system at the databroker level.
