### ISSUE TITLE
gs.<property> has no default values at XPD computer

### ISSUE THREAD

**Issue by timoHMM** [NSLS-II/bluesky#218]
gs.<property> return " No default value found for <property> trait " error on certain fields.
It includes:
TEMP_CONTROLLER, H_MOTOR, K_MOTOR, L_MOTOR, TH_MOTOR, TTH_MOTOR,
MASTER_DET

Error message and stack dump screenshots are listed below:

![bluesky_2](https://cloud.githubusercontent.com/assets/14341942/10209409/048bfd20-67a9-11e5-806b-270038746ba8.png)
![bluesky error](https://cloud.githubusercontent.com/assets/14341942/10209408/048b6eb4-67a9-11e5-898e-f7281678904e.png)

**Comment by danielballan** [comment]
Thanks for the thorough report. This exception is coming from the traitlets
package. It means that you cannot ask to see the value of that attribute
until you set one. The attribute has no default value. (Because what would
the default value be? "None" isn't valid because "None" is not a temperate
controller.) So, this is working as expected. We imagine that beam long
scientists would set this somewhere in the startup scripts in he IPythom
profile.
