### ISSUE TITLE
Reconsider how "magical" metadata updating should be

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#240]
What should happen in this scenario:

```
RE.md['color'] = blue
RE(some_scan)  # color is blue
RE(some_scan)   # color is blue
RE(some_scan, color='red')  # color is red
RE(some_scan)  # color is ?
```

I think everyone agrees that the metadata dict is *overridden* by kwargs, but it is implicitly *updated* by kwargs? Depending on your workflow, either could make sense.

Currently, it is implicitly updated. I am beginning to think that it should not be.

**Comment by ericdill** [comment]
Why not just make it toggleable?  That way everyone can handle it however they want, we do not have to have opinions on how it *should* behave and the default behavior does not particularly matter since it can be easily changed.

**Comment by klauer** [comment]
I don't like the implicit updating myself but agree that it should be an option (as @ericdill says).

**Comment by danielballan** [comment]
I had that thought too, but I worry that it will just add to the confusion -- one more option you have to know about and check that status of.

Let's hear from more people on this and decide in a couple days.

**Comment by cowanml** [comment]
the color kwarg should take precedence over, but not change, RE.md['color']

Is this a user requested feature, or just the way it was written?

I don't like the idea of something like RE.md['unintuitive_color_behavior'] = True
That's going to cause confusion.

My vote would be for users that want a shortcut to write their own,
but some sort of explicit shortcut might just be, undesirable (2 ways
to do something), not completely horrible (unexpected behavior).  Is
there some syntax that's as explicit and clear, but shorter than (I'm
assuming half the point is to be a one liner?)
   RE.md['color'] = green; RE(some_scan)
?

   RE(some_scan, color='green', change_default_color=True)  # ?
   RE(some_scan, set_default_color='green')  # ?

Those sorta look nicer, might even be easier to type?
but doesn't seem worthwhile in my opinion.


RE.md['color'] = blue
RE(some_scan)  # color is blue
RE(some_scan)  # color is blue
RE(some_scan, color='red')  # color is red
RE(some_scan)  # who would guess this would be red?!?
                # only someone aware of the "feature", or someone making
 	       # a guess because we're asking them that question :)

RE.md['color'] = blue
RE(some_scan)  # color is blue
RE(some_scan)   # color is blue
RE.md['color'] = red  # is one line of code really that burdensome
RE(some_scan)  # clearly red, same for the next
RE(some_scan)

**Comment by danielballan** [comment]
Yeah, I'm pretty convinced, @cowanml. That last point you make seems
exactly right.

As for the question of what users request, at least one user, @sbillinge,
has requested the behavior you describe. His group has spent more time
thinking about complex metadata schemes than anyone so far.
