### ISSUE TITLE
scan steps in header doesn't record exact motor step

### ISSUE THREAD

**Issue by chiahaoliu** [NSLS-II/bluesky#248]
For now, only tested in temperature scan.
In header saved, temperature scan steps are recorded as a 'string', like array[415, 415.33, 415.67, 416]
and the values recorded are not the exact values read out from motor assigned.

**Comment by danielballan** [comment]
> In header saved, temperature scan steps are recorded as a 'string'

This is because some of the metadata could include Python objects that are defined at collection time but not at retrieval time. For example, the objects that represent motors and detectors. For this reason, we uniformly store the string representation (repr). To turn the string back into a proper list, call eval() on it.

> the values recorded are not the exact values read out by the motor

Yes, these contents are saved before the scan starts; they are a record of the plan, the instructions for then scan. To get the actual values, look at the data. These are fundamentally different: what you asked the motors to do and what they actually did.

**Comment by chiahaoliu** [comment]
Thanks so much. But can you be more detailed about 'looking at the data' ? Can we get history of motor values?

**Comment by tacaswell** [comment]
The motor value should be in the event stream as data.  I suspect you might also want a `WaveformCollector` (https://github.com/NSLS-II/ophyd/pull/160/files#diff-e5b1009db99824f9bedd05c2e5534508R57) for the temperature.

**Comment by danielballan** [comment]
@chiahaoliu The `array` in question is better known as `numpy.array`. This is just how numpy arrays represent themselves as strings.

```python

In [1]: from numpy import array

In [2]: eval('array([1,2,3])')
Out[2]: array([1, 2, 3])
```

Closing this issue based on your email. Please re-open if there is more to address.
