### ISSUE TITLE
Suspender sometimes does not suspend the scans when the PV reached and went beyond threshold value

### ISSUE THREAD

**Issue by gjwillms** [NSLS-II/bluesky#389]
We have been using the following suspender to pause scans when the monochrmator's Bragg motor temperature rises above threshold value (120 degree C).

```python
dcm_bragg_temp_pv = 'XF:05IDA-OP:1{Mono:HDCM-Ax:P}T-I'
PVSuspendCeil(RE, dcm_bragg_temp_pv, 120, resume_thresh=70, sleep = 10)
```

- It has been working for some time. However, we observed two cases yesterday that the suspender did not pause the scan. The first time when it occurred, the suspender did not pause the scan and the temperature kept increasing to 140 degree C. The scan will aborted and bluesky was restarted. 
- The scan was then re-launched, and the suspender again did not pause the scan when it reaches 120 degree C. The scan was aborted. Not exception was thrown; the scan simply keep on running. 
- However, for the third time launching the scan, the suspender successfully paused the scan. The suspender was not modified during all these scans.

Are there certain conditions that may cause the suspender to fail to suspend the scans?

**Comment by danielballan** [comment]
I can't recall whether we already spoke about this offline. Our best guess is that the suspension condition was met when the RunEngine was not presently in control of execution. The can be addressed in two ways:

* Each time the RunEngine takes control of execution, check on all the "suspenders" to see if any were tripped before the RunEngine started watching. This has been done in the latest version of bluesky.
* To respond as quickly as possible to suspenders, put all experimental logic into "plans" so that the RunEngine is always in control.

We will see if we can reproduce this issue when we visit SRX with the new version of bluesky. I will close this issue now -- please reopen if it reoccurs.

Thanks again for the detailed report.
