### ISSUE TITLE
DOC: does `event` callback method get filled event?

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/bluesky#615]
Does `event` callback method get filled event?
Would it be possible to put the answer in the docs under writing custom callbacks?

**Comment by tacaswell** [comment]
No it does not.  The only place filled event documents come from is the data broker.  There is an optional 'filled' field at the top level of the of `Event` documents which has the keys which are external and a bool if they have been filled or not.  Callbacks probably should be able to handle both filled and unfilled Event.

The reason for this is that the process running the data collection (and hence emitting the documents) may not have access to the full data (either in the abstract or due to it not being flushed to disk yet) and we certainly do not want to pay the cost of getting said data.  If events came out of the RE filled, then some (most) callbacks would have to _unfill_ them.

**Comment by CJ-Wright** [comment]
So if a callback needs a filled event it should perform the filestore logic itself?

**Comment by tacaswell** [comment]
it should conditionally fill if required.

**Comment by CJ-Wright** [comment]
Awesome thank you!
