### ISSUE TITLE
Look at providing a standard set of plans for vector motors

### ISSUE THREAD

**Issue by stuartcampbell** [NSLS-II/bluesky#753]
For motors like `(hkl)` etc...

**Comment by danielballan** [comment]
@tacaswell and I came up with a way to do this over lunch that I figure we had better write down to remind ourselves in the future.

The `scan_nd` plan can determine if the motors it is passed are coupled by determining whether they belong to the same parent device (via `parent` or `root`). If they are, it can move the axes together rather than trying to control them independently. This should remove the need to do all HKL via `list_scan`.

**Comment by danielballan** [comment]
> I figure we had better write down to remind ourselves in the future.

This was prophetic. I definitely forgot this idea completely and thought it was lost forever.

**Comment by tacaswell** [comment]
closed by #873
