### ISSUE TITLE
inclusion of 'input' as a generator in bluesky.plans is causing issues with the use of pythons 'input' .

### ISSUE THREAD

**Issue by awalter-bnl** [NSLS-II/bluesky#808]

**Comment by awalter-bnl** [comment]
In part of my code I am using the python built in command 'input' to get user feedback, unfortunately in the latest release a generator called 'input' was included in bluesky-plans.py which is causing issues. Can the bluesky 'input' generator be renamed?

**Comment by danielballan** [comment]
I do think we should rename `input`, the only plan with a name that collides with a builtin. (The plan `sleep` has caused confusion too, but I would argue that that is a less acute collision because the "builtin" sleep is scoped under `time.sleep`, not in the global namespace.)

For what it's worth, this is not a change in bluesky. The `input` plan has been around for about a year. I think the change is in ESM's IPython profile, which now imports `from bluesky.plans import *` as well as `import bluesky.plans as bp`. Both styles have their advocates, and we should support both.

**Comment by danielballan** [comment]
Alternative name ideas:

* `async_input`
* `safe_input`
* `plan_input`

**Comment by danielballan** [comment]
This came up before: https://github.com/NSLS-II/bluesky/issues/578

**Comment by stuartcampbell** [comment]
I think it would be a good time to rename it now, while we are breaking things!

**Comment by kevinyager** [comment]
Agree with renaming. I think "plan_input" is the clearest name from the user perspective.

**Comment by tacaswell** [comment]
`input_plan` is a bit better (reads more like a noun "this is the plan I yield from to get input" rather than an imperative "please plan ahead for the input your about to get")

**Comment by cmazzoli** [comment]
inplan?

**Comment by danielballan** [comment]
Or maybe just the letter i? ;-)

**Comment by ambarb** [comment]
````clear_suspenders()````  would suggest action (clear) on an object (suspenders).  So are you providing input for a plan  (````input_plan````)  or planning input (````plan_input````) ?  It seems @tacaswell suggestion makes more sense.  Maybe there are other functions in bluesky that are inverted  so it might be worth thinking about which way you all want to name things in general.  I would say that ````object_action````  format makes it a bit easier to figure out which functions you want to use.  Either way, I am okay as long as things are consistent and that we slowly start to identify which things are inverted.

**Comment by danielballan** [comment]
That's a good point. I surveyed the documentation and found that we are pretty consistent in choosing names like "<verb> <object>" over "<object> <verb>" and we can stick with that here for consistency.
