### ISSUE TITLE
examples det over-writes numpy det()

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/bluesky#886]
`from bluesky.examples import det`
overwrites numpy's `det()`, which calculates the determinant of an array.  This could be useful  function so maybe `det` should be removed from `bluesky.examples` even though it will not be used as much.

I only suggest because there is chatter of changing `mv` to `mov` so as not to be confused with `%mv` or `!mv`.  This to me seems along the same lines.

**Comment by danielballan** [comment]
I always use numpy like `import numpy as np` because doing `from numpy import *` shadows some built-in functions (numpy's `sum` and `all` functions are different from the built-in Python functions of the same names).

Magics are special case. If we installed our own `%mv`, we would be shadowing IPython's `%mv` and making it totally inaccessible. In the case of `bluesky.examples.det` and `numpy.det`, these functions are scoped inside different modules, so both are accessible. Users who import them into the global namespace (like `from numpy import det`) must keep mental track of what is what. Some users (like Tom) prefer to avoid the problem by simply never ever doing this kind of import. Other users (like me) don't mind keeping mental track. The language leaves the choice up to you.

Does that make sense?

**Comment by ambarb** [comment]
Our startup files should `import bumpy as np`.  I assumed that we were not doing from `numpy import *` for the reasons you said, and that det() was there for some other reason that is not immediately obvious to me.  It sounds like you are saying that `det()` should not be there, and we need to figure out why it is so that we can eliminate it.

Thanks



I always use numpy like import numpy as np because doing from numpy import * shadows some built-in functions (numpy's sum and all functions are different from the built-in Python functions of the same names).

Magics are special case. If we installed our own %mv, we would be shadowing IPython's %mv and making it totally inaccessible. In the case of bluesky.examples.det and numpy.det, these functions are scoped inside different modules, so both are accessible. Users who import them into the global namespace (like from numpy import det) must keep mental track of what is what. Some users (like Tom) prefer to avoid the problem by simply never ever doing this kind of import. Other users (like me) don't mind keeping mental track. The language leaves the choice up to you.

Does that make sense?

**Comment by danielballan** [comment]
That seems right. You can use `git grep` to search your profiles. Closing as "not a bluesky issue" but happy to continue to help in this thread or on gitter.
