### ISSUE TITLE
LiveTable doesn't seem to work with ophyd.sim.img

### ISSUE THREAD

**Issue by chiahaoliu** [NSLS-II/bluesky#912]
With ``ophy.sim.img`` as detector, ``LiveTable`` gives an error about the format

## Expected Behavior
LiveTable should appear when running a scan plan with simulation objects.

## Current Behavior
``LiveTable`` raises an error 
````
ValueError: Unknown format code 'f' for object of type 'str'
````
when running a scan plan with simulation objects but RE call can be run after excluding ``LiveTable``

## Steps to Reproduce (for bugs)
````
from databroker import temp_config, Broker
from ophyd.sim import img, NumpySeqHandler
import bluesky.plans as bp
from bluesky.callbacks import LiveTable
from bluesky.run_engine import RunEngine

db = Broker.from_config(temp_config())
db.reg.register_handler('NPY_SEQ', NumpySeqHandler)
img.reg = db.reg

RE = RunEngine({})
RE.subscribe(db.insert, 'all')
dets = [img]

# this call would be fine
RE(bp.count(dets, num=1))

# check if metadata is pused into database
h = db[-1]
h['start']

# this would gives error described above
RE(bp.count(dets, num=1), LiveTable(dets))
````

## Your Environment
version:
``bluesky`` at ``upstream/master``
``ophyd`` at ``upstream/master``
``databroker`` at  ``upstream/master  ``

**Comment by danielballan** [comment]
Looks like an f-string sneaked into LiveTable.

**Comment by danielballan** [comment]
The `dtype` of `'img'` is float, but because it's unfilled external data, the actual content of `{'data': {'img': ...}}` is a string (a datum_id). I think the ring thing to do here is to display '<EXTERNAL>' in the table when this happens.

The easy fix is to implement `hints` and ensure the `img` is not included in the list of fields that BestEffortCallback should try to print/plot. This is what we do to real detectors on the floor.

I'd like to do the hints fix for 1.0.0 but punt the deeper change to LiveTable to a future release. Sound OK, everyone?

**Comment by danielballan** [comment]
Given the thumbs-up from @chiahaoliu on my comment above, I'm closing this issue. See the two new issues linked by GH, addressing each part of my comment.

**Comment by chiahaoliu** [comment]
Thanks for replying. I was trying to implement that ``hints`` change and glad to see it's already there :)
