### ISSUE TITLE
Per step for `count`

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/bluesky#929]
Should we have a `per_step` for count? (I think this was mentioned somewhere but I don't know/can't find where so I'm putting it here)

## Expected Behavior
Count takes in a `per_step`. When the plan is executed it does the per_step in the count's place.
Eg `count(..., per_step=take_dark)` would take a dark before taking the light image.
## Current Behavior
Count does not take a `per_step`.

## Possible Solution
Put in a `per_step` kwarg. Interestingly this raises a bit more general problem. The current `per_step` signature is `(detector, motor, step)`. However, there is no internal motor for this signature to be called upon. One thing we could do is to have two kwargs;  `per_step` and `per_step_args`. The args would be fed into `per_step` as required. This fixes some of the issues where accessing motors not in the plan (eg the shutter) is done by pulling them from the globals and hoping that they will be there. Additionally this allows for `per_steps` which don't need all/any of those arguments.

## Context
It would be nice to be able to take darks in the same start as the lights, being able to have a count `per_step` which closed the shutter and took a dark would be a nice way to handle this.

Attn: @chiahaoliu

**Comment by danielballan** [comment]
This has been raised a couple times, and I've been shooting it down because it feels like overworking `count` -- too much complexity for not much code reuse gained. I would rather this be implemented as a separate plan that just uses `trigger_and_read`. I think that would be more clear.

I'm open to dissenting arguments....

**Comment by CJ-Wright** [comment]
@tacaswell thoughts? (I think I remember a gchat discussion where you had suggested this)

**Comment by teddyrendahl** [comment]
Feels to me like a bandaid for the real problem. `count` really feels like a `plan_stubs` to me. `trigger_and_read` is a nice alternative, but reimplementing it with a for loop every time (especially with all the nice logic regarding delays e.t.c) is a pain. I don't know @CJ-Wright specific use case, but in my head I imagine that instead of `per_step` hook on count you could invert it and use `count` as the `per_step` hook on a different plan?

```python
plan = scan([det], mot, -5, 5, per_step=stub_count([det], num=10, delay=1))
```

I think the proper solution might be adding a stub plan that does the same thing as count, then have the full `bluesky.plans.count` just call this with the correct metadata. However, if you wanted to try this now you could always use the `stub_wrapper` on `count`

**Comment by ZLLentz** [comment]
Perhaps the plan should be a more generic `repeat` that has the delay/loop control flow, and `count` simply becomes `yield from repeat(*args, plan=bp.trigger_and_read, **kwargs)`.

**Comment by prjemian** [comment]
Can we leave the `count()` plan unchanged and make a different plan that is designed per this discussion?  For SPEC users, the `count` macro has some meaning.

**Comment by chiahaoliu** [comment]
@teddyrendahl Maybe I can help add more details to the use case @CJ-Wright might have in mind.

Users sometimes uses ``count`` with desired delay(s) to monitor the in-situ experiment but between  frames, user might also want customized behavior. For example, closing shutter to protect detector and sample but could be more complex.

**Comment by danielballan** [comment]
I think `repeat` is reasonable. A loop would also be fine and IMO more clear, but given that `bluesky.plans` is functionally-oriented, using a function to build a loop is at least stylistically self-consistent.

**Comment by teddyrendahl** [comment]
@chiahaoliu Interesting, I believe that @ZLLentz has the right idea here with a `repeat` plan that allows you to use all of the delay logic `count` in other plans.

```python
def shuttered_count([det], num=None, delay=None):
        
       def shuttered_measurement():
               yield from Msg('set', shutter, 'open')
               yield from trigger_and_read([det, shutter])
               yield from Msg('set', shutter', 'closed')
       
       yield from repeat(shuttered_measurement(), num=num, delay=delay)
```

**Comment by danielballan** [comment]
attn @chiahaoliu @chiahaoliu This is in. I'd be interested in feedback on whether it helps with your use case. It didn't make the cut for what we just deployed to the floor at NSLS-II, but we might deploy a minor upgrade mid-cycle.

**Comment by chiahaoliu** [comment]
@danielballan Thanks! I am starting to implement new scan plan, with the architecture introduced here. I will update the progress.
